spring:
  application:
    name: cloud-consumer-movie-ribbon
server:
  port: 7903
eureka:
  client:
    serviceUrl:
      defaultZone: http://zuster:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
ribbon:
  eureka:
   enabled: false
cloud-provider-user:
  ribbon:
    listOfServers: localhost:7910