
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://zuster:123456@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
#  server:
#    enable-self-preservation: false
security:
  basic:
    enabled: true
  user:
    name: zuster
    password: 123456